estoque/estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name='index'),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('notaEntrada.urls', namespace='entrada')),
    path('admin/', admin.site.urls),
]

estoque/notaEntrada/urls.py
from django.urls import path
from .views import notaEntradaList, notaEntradaNew, notaEntradaUpdate, notaEntradaDelete

app_name = 'notaEntrada'

urlpatterns = [
    path('notaEntradaList/', notaEntradaList, name='notaEntradaList'),
    path('notaEntradaNew/', notaEntradaNew, name='notaEntradaNew'),
    path('notaEntradaUpdate/<int:pk>/', notaEntradaUpdate, name='notaEntradaUpdate'),
    path('notaEntradaDelete/<int:pk>/', notaEntradaDelete, name='notaEntradaDelete'),
]

estoque/produto/urls.py
from django.urls import path
from .views import listar, novo, alterar, deletar

app_name = 'produto'
urlpatterns = [
    path('listar/', listar, name='listar'),
    path('novo/', novo, name='novo'),
    path('alterar/<int:pk>/', alterar, name='alterar'),
    path('deletar/<int:pk>/', deletar, name='deletar')
]

estoque/core/models.py
from django.db import models

# Create your models here.

estoque/notaEntrada/models.py
from django.db import models
from produto.models import Produtos

class NotasEntradas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.PROTECT)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    quantidade = models.IntegerField('Quantidade', default=0)

    criado = models.DateTimeField('criado', auto_now_add=True)
    modificado = models.DateTimeField('modificado', auto_now=True)

    def __str__(self) -> str:
        return self.produto.produto

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ['produto']

estoque/produto/models.py
from django.db import models

class Cores(models.Model):
    cor = models.CharField('Cor', max_length=200)

    def __str__(self) -> str:
        return self.cor

class Produtos(models.Model):
    produto = models.CharField('Produto', max_length=200)
    cor = models.ForeignKey(Cores, on_delete=models.PROTECT)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    quantidade = models.IntegerField('Quantidade', default=0)

    def __str__(self) -> str:
        return self.produto

estoque/notaEntrada/forms.py
from django.forms import ModelForm, TextInput, Select
from .models import NotasEntradas

class NotasEntradasForm(ModelForm):
    class Meta:
        model = NotasEntradas
        #fields = '__all__'
        fields = ['produto', 'quantidade', 'preco']
        widgets = {
            'produto': Select(attrs={'class': 'select'}),
            'quantidade': TextInput(attrs={'class': 'input'}),
            'preco': TextInput(attrs={'class': 'input'}),
        }

estoque/produto/forms.py
from django.forms import ModelForm
from .models import Produtos

class ProdutoForm(ModelForm):
    class Meta:
        model = Produtos
        fields = ['produto', 'cor']

estoque/core/views.py
from django.shortcuts import render

def index(request):
    template_name = 'index.html'
    context = {
        'mensagem': 'Bem vindo a aplicação estoqueWeb'
    }
    return render(request, template_name, context)

estoque/notaEntrada/views.py
from django.shortcuts import render, redirect
from .models import NotasEntradas
from .forms import NotasEntradasForm

def notaEntradaList(request):
    notas_entrada = NotasEntradas.objects.all()
    template_name = 'notaEntradaList.html'
    context = {
        'notas_entrada': notas_entrada
    }
    return render(request, template_name, context)

def notaEntradaNew(request):
    if request.method == 'POST':
        form = NotasEntradasForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:notaEntradaList')
    else:
        form = NotasEntradasForm()
        template_name = 'notaEntradaNew.html'
        context = {
            'form': form,
        }
        return render(request, template_name, context)

def notaEntradaUpdate(request, pk):
    entrada = NotasEntradas.objects.get(id=pk)
    quantidade_nota_antiga = entrada.quantidade
    if request.method == 'POST':
        form = NotasEntradasForm(request.POST, instance=entrada)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - quantidade_nota_antiga + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:notaEntradaList')
    else:
        template_name = 'notaEntradaUpdate.html'
        context = {
            'form': NotasEntradasForm(instance=entrada),
            'pk': pk
        }
        return render(request, template_name, context)

def notaEntradaDelete(request, pk):
    entrada = NotasEntradas.objects.get(id=pk)
    quantidade_nota_antiga = entrada.quantidade
    entrada.produto.quantidade = entrada.produto.quantidade - quantidade_nota_antiga
    entrada.produto.save()
    entrada.delete()
    return redirect('entrada:notaEntradaList')

estoque/produto/views.py
from django.shortcuts import render, redirect
from .models import Produtos
from .forms import ProdutoForm

def listar(request):
    produtos = Produtos.objects.all()
    template_name = 'listar_produtos.html'
    context = {
        'produtos': produtos
    }
    return render(request, template_name, context)

def novo(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('produto:listar')
    else:
        template_name = 'novo_produto.html'
        context = {
            'form': ProdutoForm(),
        }
        return render(request, template_name, context)

def alterar(request, pk):
    produto = Produtos.objects.get(id=pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('produto:listar')
    else:
        template_name = 'alterar_produto.html'
        context = {
            'form': ProdutoForm(instance=produto),
            'pk': pk,
        }
        return render(request, template_name, context)

def deletar(request, pk):
    produto = Produtos.objects.get(id=pk)
    produto.delete()
    return redirect('produto:listar')

estoque/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EstoqueWeb</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item">
                Home
            </a>
            <a class="navbar-item" href="{% url 'produto:listar' %}">Produtos</a>

            <a class="navbar-item" href="{% url 'entrada:notaEntradaList' %}">Nota Entrada</a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Jobs
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

    </div>
</nav>
<section class="section">
    <h1 class="title">Section</h1>
    <h2 class="subtitle">
        A simple container to divide your page into <strong>sections</strong>, like the one you're currently reading.
    </h2>
    {% block product %}{% endblock %}
</section>
<footer class="footer">
    <div class="content has-text-centered">
        <p>
            <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
            is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </p>
    </div>
</footer>
</body>
</html>

estoque/core/templates/index.html
{% extends 'base.html' %}

{% block product %}
    <h1>{{ mensagem }}</h1>
{% endblock %}

estoque/notaEntrada/templates/notaEntradaList.html
{% extends 'base.html' %}

{% block product %}
<a class="button is-primary" href="{% url 'entrada:notaEntradaNew' %}">Novo</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for nota_entrada in notas_entrada %}
        <tr>
            <td>{{ nota_entrada.id }}</td>
            <td>{{ nota_entrada.produto }}</td>
            <td>{{ nota_entrada.cor }}</td>
            <td>{{ nota_entrada.preco }}</td>
            <td>{{ nota_entrada.quantidade }}</td>
            <td><a class="button is-primary" href="{% url 'entrada:notaEntradaUpdate' nota_entrada.id %}">alterar</a></td>
            <td><a class="button is-primary" href="{% url 'entrada:notaEntradaDelete' nota_entrada.id %}">deletar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

estoque/notaEntrada/templates/notaEntradaNew.html
{% extends 'base.html' %}

{% block product %}
<h1>Nota Entrada</h1>

<form action="{% url 'entrada:notaEntradaNew' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
        <label class="label">{{ field.label }}</label>
        <div class="control">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <button class="button" type="submit">Salvar</button>
</form>


{% endblock %}

estoque/notaEntrada/templates/notaEntradaUpdate.html
{% extends 'base.html' %}

{% block product %}
<h1>Nota Entrada update</h1>

<form action="{% url 'entrada:notaEntradaUpdate' pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
{% endblock %}

estoque/produto/templates/alterar_produto.html
{% extends 'base.html' %}

{% block product %}
<p>Novo produto</p>

<form action="{% url 'produto:alterar' pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
{% endblock %}

estoque/produto/templates/listar_produtos.html
{% extends 'base.html' %}

{% block product %}
    <h1>Listagem de produtos</h1>
    <a href="{% url 'produto:novo' %}">Novo</a>
    <br>
    
    <table>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
            <th></th>
        </tr>
        {% for produto in produtos %}
            <tr>
                <td>{{ produto.id }}</td>
                <td>{{ produto.produto }}</td>
                <td>{{ produto.cor }}</td>
                <td>{{ produto.preco }}</td>
                <td>{{ produto.quantidade }}</td>
                <td><a href="{% url 'produto:alterar' produto.id %}">alterar</a></td>
                <td><a href="{% url 'produto:deletar' produto.id %}">deletar</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

estoque/produto/templates/novo_produto.html
{% extends 'base.html' %}

{% block product %}
<p>Novo produto</p>

<form action="{% url 'produto:novo' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
{% endblock %}